In [1]:
from pathlib import Path
import sys

import pandas as pd

ROOT = Path.cwd().parents[0]

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.risk.stress_testing import (
    run_stress_testing,
)

In [2]:
portfolio_df = pd.read_csv(
    ROOT / "data" / "portfolio" / "portfolio_daily.csv"
)

returns_df = pd.read_csv(
    ROOT / "data" / "raw" / "returns.csv"
)

weights_df = pd.read_csv(
    ROOT / "data" / "portfolio" / "portfolio_weights.csv"
)

sectors_df = pd.read_csv(
    ROOT / "data" / "raw" / "sectors.csv"
)

In [3]:
results_df, ranking_df, observations_df = run_stress_testing(
    portfolio_returns=portfolio_df,
    asset_returns=returns_df,
    weights=weights_df,
    sectors=sectors_df,
    confidence=0.99,
)

WARNING: No portfolio observations found for 2008 Financial Crisis: 2008-09-01 to 2008-12-31

In [4]:
results_df

,Scenario,Scenario Type,Start Date,End Date,Observations,Stressed Portfolio Loss,Stressed VaR,Stressed Expected Shortfall,Worst-Case Loss,Worst Loss Date,Shocked Sector,Sector Portfolio Weight
0,COVID Crash 2020,Historical,2020-02-19,2020-03-23,24,0.148607,0.138124,0.148607,0.148607,2020-03-16,NaN,NaN
1,Inflation Shock 2022,Historical,2022-01-03,2022-10-12,196,0.062256,0.051654,0.058469,0.062256,2022-09-13,NaN,NaN
2,Banking Stress 2023,Historical,2023-03-01,2023-05-05,47,0.022396,0.021189,0.022396,0.022396,2023-03-09,NaN,NaN
3,Tech Selloff,Historical,2022-01-03,2022-06-16,115,0.054683,0.051350,0.053089,0.054683,2022-05-05,NaN,NaN
4,Equity Market Down 5%,Hypothetical,NaT,NaT,1652,0.050000,0.099400,0.116158,0.198607,NaT,NaN,NaN
5,Equity Market Down 10%,Hypothetical,NaT,NaT,1652,0.100000,0.149400,0.166158,0.248607,NaT,NaN,NaN
6,Equity Market Down 20%,Hypothetical,NaT,NaT,1652,0.200000,0.249400,0.266158,0.348607,NaT,NaN,NaN
7,Volatility Doubles,Hypothetical,NaT,NaT,1652,0.298188,0.099776,0.133291,0.298188,NaT,NaN,NaN
8,Correlation Spikes,Hypothetical,NaT,NaT,1652,0.137655,0.047693,0.063432,0.137655,NaT,NaN,NaN
9,Sector-Specific Shock - Technology - 20%,Hypothetical,NaT,NaT,1652,0.100000,0.100000,0.100000,0.100000,NaT,Technology,0.5

In [5]:
ranking_df

,Rank,Scenario,Scenario Type,Stressed Portfolio Loss,Stressed VaR,Stressed Expected Shortfall,Worst-Case Loss
0,1,Equity Market Down 20%,Hypothetical,0.200000,0.249400,0.266158,0.348607
1,2,Volatility Doubles,Hypothetical,0.298188,0.099776,0.133291,0.298188
2,3,Equity Market Down 10%,Hypothetical,0.100000,0.149400,0.166158,0.248607
3,4,Equity Market Down 5%,Hypothetical,0.050000,0.099400,0.116158,0.198607
4,5,COVID Crash 2020,Historical,0.148607,0.138124,0.148607,0.148607
5,6,Correlation Spikes,Hypothetical,0.137655,0.047693,0.063432,0.137655
6,7,Sector-Specific Shock - Technology - 20%,Hypothetical,0.100000,0.100000,0.100000,0.100000
7,8,Inflation Shock 2022,Historical,0.062256,0.051654,0.058469,0.062256
8,9,Tech Selloff,Historical,0.054683,0.051350,0.053089,0.054683
9,10,Banking Stress 2023,Historical,0.022396,0.021189,0.022396,0.022396

In [6]:
ranking_df.iloc[0]

Rank                                                1
Scenario                       Equity Market Down 20%
Scenario Type                            Hypothetical
Stressed Portfolio Loss                           0.2
Stressed VaR                                   0.2494
Stressed Expected Shortfall                  0.266158
Worst-Case Loss                              0.348607
Name: 0, dtype: object